-- ============================================================
-- ASTHRA 2K26 IMPOSTER — Canonical Database Migration
-- Run once against a fresh Supabase project.
-- Safe to re-run: all statements use IF NOT EXISTS / ON CONFLICT DO NOTHING.
-- DO NOT run seed_test_data.sql against production.
-- ============================================================

-- ── 1. teams ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS teams (
    id         SERIAL       PRIMARY KEY,
    team_name  TEXT         NOT NULL UNIQUE,
    team_code  TEXT         NOT NULL UNIQUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ── 2. participants ───────────────────────────────────────────────────────────
-- id is a UUID generated by Supabase (gen_random_uuid()).
CREATE TABLE IF NOT EXISTS participants (
    id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    team_id          INTEGER      NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    participant_name TEXT         NOT NULL,
    player_role      TEXT,          -- 'Imposter' | 'Specialist' | NULL (pre-shuffle)
    shuffle_group    TEXT,          -- 'Group 1' … 'Group 6' | NULL (pre-shuffle)
    is_imposter      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_participants_team_id ON participants (team_id);

-- ── 3. main_event_tasks ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS main_event_tasks (
    id               SERIAL       PRIMARY KEY,
    task_number      INTEGER      NOT NULL UNIQUE,
    task_title       TEXT         NOT NULL,
    task_description TEXT         NOT NULL,

    person1_title    TEXT         NOT NULL,
    person1_work     TEXT         NOT NULL,

    person2_title    TEXT         NOT NULL,
    person2_work     TEXT         NOT NULL,

    person3_title    TEXT         NOT NULL,
    person3_work     TEXT         NOT NULL,

    person4_title    TEXT         NOT NULL,
    person4_work     TEXT         NOT NULL,   -- cover job (visible to imposter as cover)
    person4_secret   TEXT         NOT NULL,   -- secret sabotage (only shown to imposter)

    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ── 4. Task seeds (idempotent) ────────────────────────────────────────────────

INSERT INTO main_event_tasks (
    task_number, task_title, task_description,
    person1_title, person1_work,
    person2_title, person2_work,
    person3_title, person3_work,
    person4_title, person4_work, person4_secret
) VALUES (
    1,
    'The 45-Minute Game Plan',
    'Build an interactive photo gallery web app as a team. Each member handles a distinct layer of the UI and functionality. One member is secretly the Imposter with a hidden sabotage objective.',

    'The Frame Maker',
    'Time to code: 20 mins | Testing: 10 mins. Create 4 to 6 picture cards with white borders and simple text captions. Goal: Make the main gallery wall look clean and ready to display photos.',

    'The Vibe Switcher',
    'Time to code: 20 mins | Testing: 10 mins. Add 3 simple buttons at the top ("B&W", "Vintage", "Reset"). Goal: Add a quick CSS rule so clicking the buttons changes the photo colors.',

    'The Party Popper',
    'Time to code: 25 mins | Testing: 10 mins. Build a basic click-to-zoom effect. Goal: Make it so clicking a photo opens it bigger on the screen with a dark overlay backdrop.',

    'The Imposter',
    'Time to code: 25 mins | Testing: 10 mins. Cover Job: Build the "Like Button & Reaction Counter" on every photo card so the team thinks you are just making an interactive favorite feature.',
    'SECRET TRAP: Hide the chaos code inside one specific photo''s Like button! If someone clicks that specific photo''s heart 3 times fast, it activates "Chaos Mode" — swaps all photos to silly memes or spins the page. Do NOT reveal this to anyone.'
) ON CONFLICT (task_number) DO NOTHING;

INSERT INTO main_event_tasks (
    task_number, task_title, task_description,
    person1_title, person1_work,
    person2_title, person2_work,
    person3_title, person3_work,
    person4_title, person4_work, person4_secret
) VALUES (
    2,
    'Food Cart Builder',
    'Build a food ordering web app as a team. Each member owns a specific feature layer. One member is secretly the Imposter with a hidden inflation sabotage objective.',

    'The UI & Grid Designer',
    'Goal: Build a visual grid of food cards. Key Features: Render dynamic cards containing item images/emojis, dish titles, descriptions, and price tags. Include an "Add to Cart" button on each card. Technical Focus: Component layout (CSS Grid/Flexbox), rendering lists from a JSON dataset.',

    'The Logic Lead',
    'Goal: Create a navigation toolbar that controls what shows up on the screen. Key Features: Filter buttons for "All", "Snacks", "Drinks", and "Desserts", plus a search bar for specific items. Technical Focus: Array filtering methods (.filter()), passing active category states.',

    'The State Manager',
    'Goal: Build a slide-out drawer that tracks selections and handles financial math. Key Features: A side panel displaying selected items, quantity increments/decrements (+/-), subtotal calculation, tax calculation, and a final total. Technical Focus: State aggregation, JavaScript .reduce() for sum totals, drawer open/close animations.',

    'The Imposter',
    'Cover Job: Build a quick tip selection bar ($1, $2, $5, or Custom %).',
    'SECRET TRAP ("Inflation Crisis"): Attach a hidden setInterval listener to the $5 Tip button. When clicked, it initiates a loop that increases the final bill by $100 every 50 milliseconds until it hits $999,999. Optional visual touch: Flashes the screen red and adds warning text: "INFLATION RUNAWAY DETECTED." Do NOT reveal this to anyone.'
) ON CONFLICT (task_number) DO NOTHING;

INSERT INTO main_event_tasks (
    task_number, task_title, task_description,
    person1_title, person1_work,
    person2_title, person2_work,
    person3_title, person3_work,
    person4_title, person4_work, person4_secret
) VALUES (
    3,
    'Event Fortune Teller / Wheel of Destiny',
    'Build a mysterious interactive carnival booth where attendees get custom event predictions. One member is secretly the Imposter with a hidden Y2K meltdown sabotage objective.',

    'The Mystic Crystal',
    'Build the main central crystal ball or spinning wheel element with glowing CSS borders and mystical background vibes.',

    'The Fortune Generator',
    'Create 5 selector buttons ("Will I win a prize?", "Who is my event match?", "My future today", "My lucky number", "What awaits me?") that display random fortune cards.',

    'The Audio Oracle',
    'Add eerie/fun sound effect buttons (Gong, Magic Chime, Suspense Drum) that play during fortune readings.',

    'The Imposter',
    'Cover Job: Build a "Enter Your Birth Year" drop-down box to "customize" predictions.',
    'SECRET TRAP: Selecting the year "1999" triggers Y2K Meltdown — glitchy text rapidly overrides the entire screen, turning the font to neon green matrix code and flashing fake error alerts. Do NOT reveal this to anyone.'
) ON CONFLICT (task_number) DO NOTHING;

-- ── 5. main_event_assignments ─────────────────────────────────────────────────
-- participant_id is UUID matching participants.id.
-- One row per participant; written fresh on every shuffle.
CREATE TABLE IF NOT EXISTS main_event_assignments (
    id                      SERIAL       PRIMARY KEY,

    participant_id          UUID         NOT NULL UNIQUE
                                         REFERENCES participants(id)
                                         ON DELETE CASCADE,

    participant_name        TEXT         NOT NULL,
    original_team           TEXT         NOT NULL,
    shuffled_group          TEXT         NOT NULL,           -- 'Group 1' … 'Group 6'

    task_number             INTEGER      NOT NULL,
    task_title              TEXT         NOT NULL,
    task_description        TEXT         NOT NULL,

    person_slot             INTEGER      NOT NULL,           -- 1/2/3 = specialist, 4 = imposter
    role_name               TEXT         NOT NULL,
    work_description        TEXT         NOT NULL,
    is_imposter             BOOLEAN      NOT NULL DEFAULT FALSE,

    -- Submission
    github_repo             TEXT,
    github_owner            TEXT,
    github_repo_name        TEXT,
    github_branch           TEXT,
    submission_status       TEXT         NOT NULL DEFAULT 'Pending',  -- Pending|Submitted|Evaluated|Failed
    submission_locked       BOOLEAN      NOT NULL DEFAULT FALSE,
    submitted_at            TIMESTAMPTZ,

    -- AI Evaluation
    evaluation_status       TEXT         NOT NULL DEFAULT 'Pending',  -- Pending|Evaluating|Evaluated|Failed
    ai_score                NUMERIC,
    ui_score                INTEGER,
    task_match_score        INTEGER,
    logic_score             INTEGER,
    creativity_score        INTEGER,
    code_quality_score      INTEGER,
    ai_feedback             TEXT,

    -- Scoring accumulators
    main_event_score        INTEGER      NOT NULL DEFAULT 0,
    fizzbuzz_score          INTEGER      NOT NULL DEFAULT 0,
    fizzbuzz_team_score     INTEGER      NOT NULL DEFAULT 0,
    fizzbuzz_speed_bonus    INTEGER      NOT NULL DEFAULT 0,
    imposter_bonus          INTEGER      NOT NULL DEFAULT 0,
    fizzbuzz_locked         BOOLEAN      NOT NULL DEFAULT FALSE,
    fizzbuzz_completed      BOOLEAN      NOT NULL DEFAULT FALSE,
    total_individual_score  INTEGER      NOT NULL DEFAULT 0,

    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mea_participant_id   ON main_event_assignments (participant_id);
CREATE INDEX IF NOT EXISTS idx_mea_shuffled_group   ON main_event_assignments (shuffled_group);
CREATE INDEX IF NOT EXISTS idx_mea_submission_status ON main_event_assignments (submission_status);

-- ── 6. shuffle_lock ───────────────────────────────────────────────────────────
-- Prevents accidental re-shuffle after event starts.
-- Coordinator must explicitly unlock before re-shuffling.
CREATE TABLE IF NOT EXISTS shuffle_lock (
    id          INTEGER      PRIMARY KEY DEFAULT 1,  -- only one row
    is_locked   BOOLEAN      NOT NULL DEFAULT FALSE,
    locked_at   TIMESTAMPTZ,
    locked_by   TEXT,
    CONSTRAINT  single_row CHECK (id = 1)
);

INSERT INTO shuffle_lock (id, is_locked) VALUES (1, FALSE)
ON CONFLICT (id) DO NOTHING;

-- ── 7. event_timers ───────────────────────────────────────────────────────────
-- Authoritative server-side timer table.
-- event_key is TEXT PRIMARY KEY for easy lookup.
CREATE TABLE IF NOT EXISTS event_timers (
    event_key         TEXT         PRIMARY KEY,
    event_name        TEXT         NOT NULL,
    duration_minutes  INTEGER      NOT NULL,
    started_at        TIMESTAMPTZ,
    paused_at         TIMESTAMPTZ,
    remaining_seconds INTEGER      NOT NULL,
    status            TEXT         NOT NULL DEFAULT 'idle',  -- idle|running|paused|finished
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

INSERT INTO event_timers (event_key, event_name, duration_minutes, remaining_seconds, status) VALUES
  ('main_event',    'Main Event',      45, 2700, 'idle'),
  ('fizzbuzz',      'FizzBuzz',        15,  900, 'idle'),
  ('code_imposter', 'Code Imposter',   20, 1200, 'idle'),
  ('sherlock',      'Sherlock Holmes', 45, 2700, 'idle')
ON CONFLICT (event_key) DO NOTHING;

-- ── 8. fizzbuzz_submissions_v2 ────────────────────────────────────────────────
-- One submission per shuffled group.
CREATE TABLE IF NOT EXISTS fizzbuzz_submissions_v2 (
    shuffled_group      TEXT         PRIMARY KEY,
    submitted_by        TEXT         NOT NULL,
    participant_id      TEXT         NOT NULL,
    fizz_output         TEXT,
    language            TEXT         NOT NULL DEFAULT 'Unknown',
    repo_url            TEXT,
    submitted_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    status              TEXT         NOT NULL DEFAULT 'Submitted',
    is_correct          BOOLEAN,
    speed_bonus         INTEGER      NOT NULL DEFAULT 0,
    imposter_bonus      INTEGER      NOT NULL DEFAULT 0,
    imposter_sabotaged  BOOLEAN      NOT NULL DEFAULT FALSE
);

-- ── 9. code_imposter_submissions ─────────────────────────────────────────────
-- Fixes the broken frontend-only codeimposter.html
CREATE TABLE IF NOT EXISTS code_imposter_submissions (
    id               SERIAL       PRIMARY KEY,
    participant_id   UUID         REFERENCES participants(id) ON DELETE SET NULL,
    participant_name TEXT         NOT NULL,
    original_team    TEXT         NOT NULL,
    elapsed_time     TEXT         NOT NULL,
    submitted_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ── 10. manual_event_scores_v2 ────────────────────────────────────────────────
-- Flat schema: one row per original team.
CREATE TABLE IF NOT EXISTS manual_event_scores_v2 (
    original_team  TEXT        PRIMARY KEY,
    code_imposter  INTEGER     NOT NULL DEFAULT 0,
    sherlock       INTEGER     NOT NULL DEFAULT 0,
    drawing        INTEGER     NOT NULL DEFAULT 0,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── 11. admin_sessions ────────────────────────────────────────────────────────
-- Simple token-based admin session table.
-- Tokens are 64-char random hex strings generated by the server.
CREATE TABLE IF NOT EXISTS admin_sessions (
    token       TEXT         PRIMARY KEY,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMPTZ  NOT NULL DEFAULT (NOW() + INTERVAL '12 hours')
);

-- Auto-expire old sessions (background cleanup friendly)
CREATE INDEX IF NOT EXISTS idx_admin_sessions_expires ON admin_sessions (expires_at);

-- ── 12. audit_log ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS audit_log (
    id          SERIAL       PRIMARY KEY,
    action      TEXT         NOT NULL,
    performed_by TEXT,
    target      TEXT,
    details     JSONB,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_log_created ON audit_log (created_at DESC);
